spring.application.name=springai-chatbot-rag

# postgresql 과 pgvector 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=raguser
spring.datasource.password=ragpass
spring.datasource.driver-class-name=org.postgresql.Driver

# PGVector 설정
# 기본값 - 벡터검색에 사용할 인덱스의 유형 고성능 근사 근접 이웃 검색을 위한 익덱스 방식
spring.ai.vectorstore.pgvector.index-type=HNSW
# 기본값 - 벡터간의 유사도를 측정할 때 사용할 거리 계산 방식 (값이 작을 수록 유사하다)
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
# 기본값 - 벡터의 차원수 - 1536은 OpenAI의 GPT모델에서 생성된 임베딩의 기본 벡터 차원
spring.ai.vectorstore.pgvector.dimensions=1536
# 벡터의 차원수 - 2304는 Gemma2 2G의 모델에서 생성된 임베딩의 기본 벡터 차원
#spring.ai.vectorstore.pgvector.dimensions=2304


spring.ai.vectorstore.pgvector.initialize-schema=true

#jpa 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Ollama 서버 주소
spring.ai.ollama.base-url=http://localhost:11434
# 모델 다운로드 전략(always: 항상 pull, when_missing:없으면 pull, never: pull 안함) 
spring.ai.ollama.init.pull-model-strategy=when_missing

# 기본 셋팅 llm모델
#spring.ai.ollama.chat.model=qwen3:8b   # 8G

# 2G
#spring.ai.ollama.chat.model=llama3.2:3b
# 4.9G
#spring.ai.ollama.chat.model=llama3.1:8b

# 4.9G
spring.ai.ollama.chat.model=gemma2:2b


# 1G
#spring.ai.ollama.chat.model=qwen3.5:0.8b
# 1.4G
#spring.ai.ollama.chat.model=qwen3:1.7b
# 2.7G
#spring.ai.ollama.chat.model=qwen3.5:2b
# 3.4G
#spring.ai.ollama.chat.model=qwen3.5:4b


# 모델초기화시 최대 대기시간
#spring.ai.ollama.init.timeout=60s

# 모델초기화 실패시 재시도 회수
#spring.ai.ollama.init.max-retries=1

# 창의성 조절: 높을수록 자유로운 응답
spring.ai.ollama.chat.options.temperature=0.3
#spring.ai.ollama.chat.options.temperature=0.1

# 최대 응답 토큰 수
spring.ai.ollama.chat.options.max-tokens=1024

# Embedding 모델
spring.ai.ollama.embedding.model=bona/bge-m3-korean