spring.application.name=springai-chatbot

# Ollama 서버 주소
spring.ai.ollama.base-url=http://localhost:11434
# 모델 다운로드 전략(always: 항상 pull, when_missing:없으면 pull, never: pull 안함) 
spring.ai.ollama.init.pull-model-strategy=when_missing

# 기본 셋팅 llm모델
#spring.ai.ollama.chat.model=qwen3:8b   # 8G

# 2G
#spring.ai.ollama.chat.model=llama3.2:3b
# 4.9G
#spring.ai.ollama.chat.model=llama3.1:8b

# 4.9G
spring.ai.ollama.chat.model=gemma2:2b


# 1G
#spring.ai.ollama.chat.model=qwen3.5:0.8b
# 1.4G
#spring.ai.ollama.chat.model=qwen3:1.7b
# 2.7G
#spring.ai.ollama.chat.model=qwen3.5:2b
# 3.4G
#spring.ai.ollama.chat.model=qwen3.5:4b


# 모델초기화시 최대 대기시간
#spring.ai.ollama.init.timeout=60s

# 모델초기화 실패시 재시도 회수
#spring.ai.ollama.init.max-retries=1

# 창의성 조절: 높을수록 자유로운 응답
spring.ai.ollama.chat.options.temperature=0.3
#spring.ai.ollama.chat.options.temperature=0.1

# 최대 응답 토큰 수
spring.ai.ollama.chat.options.max-tokens=1024

# Embedding 모델
spring.ai.ollama.embedding.model=bona/bge-m3-korean